package daniele.progetto_mongo.utility;

public enum Contratto {
    ACCESSORIO,
    APPRENDISTATO,
    APPRENDISTATOPROFESSIONALIZZANTE,
    SUBORDINATOODIPENDENTE,
    PARTTIME,
    INDETERMINATO,
    DETERMINATO,
    AUTONOMO,
    INSERIMENTO,
    INTERMITTENTE,
    RIPARTITO,
    COLLABORAZIONEOCCASIONALE,
    COLLABORAZIONEPROGETTO,
    APPRENDISTATOQUALIFICAPOSTDIPLOMA,
    APPRENDISTATOALTAFORMAZIONEERICERCA,
    STAGETIROCINI,
    NS;
}
